// TODO delete after utilities added to the db
const admin = require('firebase-admin');
const db = admin.firestore();
const utilitiesCollection = db.collection("utilities");

exports.createUtilitiesDoc = (req, res) => {
    const activitiesDe =
        [
            'Gaming',
            'Fußball',
            'Fitness',
            'Schwimmen',
            'Handball',
            'Basketball',
            'Tischtennis',
            'Tennis',
            'Reiten',
            'Yoga',
            'Pilates',
            'Squash',
            'Rudern',
            'Kanu',
            'Leichtathletik',
            'Musik',
            'Kochen',
            'Wandern',
            'Angeln',
            'Bergsteigen',
            'Camping',
            'Filmen',
            'Bouldern',
            'Klettern',
            'Bowling',
            'Kegeln',
            'Dart',
            'Kickern',
            'Golf',
            'Inlineskating',
            'Jagen',
            'Joggen',
            'Literatur',
            'Segeln',
            'Shopping',
            'Snowboarden',
            'Surfen',
            'Tanzen',
            'Tauchen',
            'Skifahren'
        ];
    const activitiesEn =
        [
            'gaming',
            'soccer',
            'fitness',
            'swimming',
            'handball',
            'basketball',
            'table tennis',
            'tennis',
            'horseback riding',
            'yoga',
            'pilates',
            'squash',
            'rowing',
            'canoe',
            'athletics',
            'Music',
            'Cooking',
            'hiking',
            'fishing',
            'mountaineering',
            'camping',
            'filming',
            'bouldering',
            'Climbing',
            'bowling',
            'skittles',
            'dart',
            'foosball',
            'golf',
            'inline skating',
            'hunting',
            'jogging',
            'literature',
            'Sailing',
            'shopping',
            'snowboarding',
            'surfing',
            'dancing',
            'Diving',
            'skiing'
        ]
    const citiesDe =
        [
            'Berlin',
            'Hamburg',
            'München',
            'Köln',
            'Frankfurt am Main',
            'Stuttgart',
            'Düsseldorf',
            'Dortmund',
            'Essen',
            'Leipzig',
            'Bremen',
            'Dresden',
            'Hannover',
            'Nürnberg',
            'Duisburg',
            'Bochum',
            'Wuppertal',
            'Bielefeld',
            'Bonn',
            'Münster',
            'Karlsruhe',
            'Mannheim',
            'Augsburg',
            'Wiesbaden',
            'Mönchengladbach',
            'Gelsenkirchen',
            'Braunschweig',
            'Kiel',
            'Chemnitz',
            'Aachen',
            'Halle (Saale)',
            'Magdeburg',
            'Freiburg im Breisgau',
            'Krefeld',
            'Lübeck',
            'Mainz',
            'Erfurt',
            'Oberhausen',
            'Rostock',
            'Kassel',
            'Hagen',
            'Saarbrücken',
            'Hamm',
            'Potsdam',
            'Mülheim an der Ruhr',
            'Ludwigshafen am Rhein',
            'Oldenburg',
            'Osnabrück',
            'Leverkusen',
            'Heidelberg',
            'Solingen',
            'Darmstadt',
            'Herne',
            'Neuss',
            'Regensburg',
            'Paderborn',
            'Ingolstadt',
            'Offenbach am Main',
            'Würzburg',
            'Fürth',
            'Ulm',
            'Heilbronn',
            'Pforzheim',
            'Wolfsburg',
            'Göttingen',
            'Bottrop',
            'Reutlingen',
            'Koblenz',
            'Recklinghausen',
            'Bremerhaven',
            'Bergisch Gladbach',
            'Jena',
            'Erlangen',
            'Remscheid',
            'Trier',
            'Salzgitter',
            'Moers',
            'Siegen',
            'Hildesheim',
            'Cottbus',
            'Frankfurt (Oder)'
        ]
    const citiesEn =
        [
            'Berlin',
            'Hamburg',
            'Munich',
            'Cologne',
            'Frankfurt am Main',
            'Stuttgart',
            'Düsseldorf',
            'Dortmund',
            'Essen',
            'Leipzig',
            'Bremen',
            'Dresden',
            'Hanover',
            'Nuremberg',
            'Duisburg',
            'Bochum',
            'Wuppertal',
            'Bielefeld',
            'Bonn',
            'Muenster',
            'Karlsruhe',
            'Mannheim',
            'Augsburg',
            'Wiesbaden',
            'Mönchengladbach',
            'Gelsenkirchen',
            'Brunswick',
            'Kiel',
            'Chemnitz',
            'Aachen',
            'Halle (Saale)',
            'Magdeburg',
            'Freiburg im Breisgau',
            'Krefeld',
            'Lübeck',
            'Mainz',
            'Erfurt',
            'Oberhausen',
            'Rostock',
            'Kassel',
            'Hagen',
            'Saarbrücken',
            'Hamm',
            'Potsdam',
            'Mülheim an der Ruhr',
            'Ludwigshafen on the Rhine',
            'Oldenburg',
            'Osnabrück',
            'Leverkusen',
            'Heidelberg',
            'Solingen',
            'Darmstadt',
            'Herne',
            'Neuss',
            'Regensburg',
            'Paderborn',
            'Ingolstadt',
            'Offenbach am Main',
            'Würzburg',
            'Fürth',
            'Ulm',
            'Heilbronn',
            'Pforzheim',
            'Wolfsburg',
            'Göttingen',
            'Bottrop',
            'Reutlingen',
            'Koblenz',
            'Recklinghausen',
            'Bremerhaven',
            'Bergisch Gladbach',
            'Jena',
            'Erlangen',
            'Remscheid',
            'Trier',
            'Salzgitter',
            'Moers',
            'Siegen',
            'Hildesheim',
            'Cottbus',
            'Frankfurt (Oder)'
        ]
    const offersDe =
        [
            'Kochen',
            'Programmieren Java',
            'Programmieren JavaScript',
            'Programmieren SQL',
            'Programmieren Python',
            'Programmieren C++',
            'Programmieren C#',
            'Programmieren HTML/CSS',
            'Programmieren Java',
            'Programmieren PHP',
            'Sprache Deutsch',
            'Sprache Englisch',
            'Sprache Französisch',
            'Sprache Italienisch',
            'Sprache Mandarin',
            'Sprache Japanisch',
            'Sprache Spanisch',
            'Sprache Portugiesisch',
            'Sprache Bosnisch',
            'Sprache Bulgarisch',
            'Sprache Dänisch',
            'Sprache Finnisch',
            'Sprache Griechisch',
            'Sprache Irisch',
            'Sprache Isländisch',
            'Sprache Italienisch',
            'Sprache Kroatisch',
            'Sprache Niederländisch',
            'Sprache Norwegisch',
            'Sprache Polnisch',
            'Sprache Rumänisch',
            'Sprache Russisch',
            'Sprache Schwedisch',
            'Sprache Slowenisch',
            'Sprache Tschechisch',
            'Sprache Türkisch',
            'Sprache Ukrainisch',
            'Sprache Ungarisch',
            'Sprache Vietnamesisch',
            'Sprache Weißrussisch',
            'Rhetorik',
            'Sport Fußball',
            'Sport Fitness',
            'Sport Schwimmen',
            'Sport Handball',
            'Sport Basketball',
            'Sport Tischtennis',
            'Sport Tennis',
            'Sport Reiten',
            'Sport Yoga',
            'Sport Pilates',
            'Sport Squash',
            'Sport Rudern',
            'Sport Kanu',
            'Sport Segeln',
            'Sport Leichtathletik',
            'Sport Volleyball',
            'Sport Dart',
            'Sport Bowling',
            'Sport Golf',
            'Gesang',
            'Musikinstrument Schlagzeug',
            'Musikinstrument Gitarre',
            'Musikinstrument Trompete',
            'Musikinstrument Posaune',
            'Musikinstrument Bass',
            'Musikinstrument Kontrabass',
            'Musikinstrument Violine',
            'Musikinstrument Bratsche',
            'Musikinstrument Cembalo',
            'Musikinstrument Klavier',
            'Musikinstrument Querflöte',
            'Musikinstrument Blockflöte',
            'Musikinstrument Oboe',
            'Musikinstrument Fagott',
            'Musikinstrument Saxophon',
            'Musikinstrument Percussion',
            'Poker',
            'Schach',
            'Backgammon',
            'Black Jack',
            'Skat',
            'Zaubertricks',
            'Computerspiel FIFA',
            'Computerspiel Counter-Strike',
            'Computerspiel League of Legends',
            'Computerspiel World of Warcraft',
            'Computerspiel Call of Duty'
        ]
    const offersEn =
        [
            'Cooking',
            'Programming Java',
            'Programming JavaScript',
            'Programming SQL',
            'Programming Python',
            'Programming C++',
            'Programming C#',
            'Programming HTML/CSS',
            'Programming Java',
            'Programming PHP',
            'Language German',
            'Language English',
            'Language French',
            'Language Italian',
            'Language Mandarin',
            'Language Japanese',
            'Language Spanish',
            'Language Portuguese',
            'Language Bosnian',
            'Language Bulgarian',
            'Language Danish',
            'Language Finnish',
            'Language Greek',
            'Language Irish',
            'Language Icelandic',
            'Language Italian',
            'Language Croatian',
            'Language Dutch',
            'Language Norwegian',
            'Language Polish',
            'Language Romanian',
            'Language Russian',
            'Language Swedish',
            'Language Slovenian',
            'Language Czech',
            'Language Turkish',
            'Language Ukrainian',
            'Language Hungarian',
            'Language Vietnamese',
            'Language Belarusian',
            'Rhetoric',
            'Sports Football',
            'Sports Fitness',
            'Sports Swimming',
            'Sports Handball',
            'Sports Basketball',
            'Sports table tennis',
            'Sports Tennis',
            'Sport Riding',
            'Sport Yoga',
            'Sport Pilates',
            'Sports squash',
            'Sport rowing',
            'Sports canoe',
            'Sport Sailing',
            'Sports athletics',
            'Sports Volleyball',
            'Sport Dart',
            'Sport bowling',
            'Sports Golf',
            'Singing',
            'Musical instrument drums',
            'Musical instrument guitar',
            'Musical instrument trumpet',
            'Musical instrument trombone',
            'Musical instrument bass',
            'Musical instrument double bass',
            'Musical instrument violin',
            'Musical instrument viola',
            'Musical instrument Harpsichord',
            'Musical instrument piano',
            'Musical instrument transverse flute',
            'Musical instrument recorder',
            'Musical instrument oboe',
            'Musical instrument bassoon',
            'Musical instrument Saxophone',
            'Musical instrument Percussion',
            'Poker',
            'Chess',
            'Backgammon',
            'Black Jack',
            'Skat',
            'Magic tricks',
            'Computer game FIFA',
            'Computer game Counter-Strike',
            'Computer game League of Legends',
            'Computer game World of Warcraft',
            'Computer game Call of Duty'
        ]
    const sexDe =
    [
        'weiblich',
        'männlich'
    ]
    const sexEn =
    [
        'female',
        'male'
    ]

    utilitiesCollection.doc('utilitiesDoc').set({
        activitiesDe: activitiesDe,
        activitiesEn: activitiesEn,
        citiesDe: citiesDe,
        citiesEn: citiesEn,
        offersDe: offersDe,
        offersEn: offersEn,
        sexDe: sexDe,
        sexEn: sexEn
    })
        .then(() => {
            return res.send(true);
        })
        .catch((error) => {
            console.log(error);
            return res.send(false)
        })
}